### ISSUE TITLE
Agregar redundancia activa del directorio

### ISSUE THREAD

**Issue by JPCard** [JPCard/TP-AyDS-II#113]
- [x] Crear un nuevo directorio.

- [x] Retransmitir heartbeats que le llegan a un directorio hacia el otro.

- [x] Evitar bucles de heartbeats (una flag que indique si es retransmitido por ej).

- [x] Cuando un directorio se inicia hacer que le pida al otro directorio los destinatarios registrados como si fuera un emisor.

- [x] Cuando emisores, sistema de mensajeria o receptores hacen pedidos al directorio y este no contesta pasaran a comunicarse con el otro directorio.

- [x] Cada componente que almacena parámetros de directorio debe agregar parámetros adicionales para otro directorio (inclusive cada directorio debe almacenar datos del otro).

**Comment by mau-lima** [comment]
En #154 y anteriores se completan los primeros 4
