### ISSUE TITLE
El panel estado de conexion y la lista de destinatarios no estan ordenados alfabeticamente

### ISSUE THREAD

**Issue by mau-lima** [JPCard/TP-AyDS-II#37]

**Comment by JPCard** [comment]
Sacamos todos los destinatarios cada vez que llega la lista actualizada y los volvemos a meter otra vez cuando llega actualizado.
Esto nos genera dos problemas:

- cuando sacas la lista original te borra la selección que estaba puesta.
**Solución:** 
Guardarse los ID de los receptores seleccionados en una estructura y cuando se genere la nueva lista volver a seleccionarlos.

- que pasa si mando un mensaje en el momento en el que me saca la lista de destinatarios registrados? -> crashearia porque no hay destinatarios seleccionados para haces el getDestinatarios.
**Solucion:**
Se podria arreglar haciendo sync sobre la lista de destinatarios registrados el metodo de cargarContactos y el de EnviarMensaje.
